### ISSUE TITLE
Cannot load python modules from conda environments when using callr

### ISSUE THREAD

**Issue by mattwarkentin** [r-lib/callr#160]
My issue seems possibly related to #155. I am unable to load `python` modules which exist only in a specific `conda` environment when I am using `{callr}`.

Some examples of what works and what doesn't. The first one works because `"os"` is a base module in `python`. The second doesn't work because it can't find `keras` in a vanilla launch of `python`. In the third example, when I actually load the correct `conda` environment that has `keras` installed, it creates a more cryptic error (traceback included) which I haven't been able to solve as of yet.
``` r
callr::r(
  function() {
    reticulate::import("os")
  }
)
#> <environment: 0x7f976a878d78>
#> attr(,"class")
#> [1] "python.builtin.module" "python.builtin.object"
```
``` r
callr::r(
  function() {
    reticulate::import("keras")
  }
)
#> Error: callr subprocess failed: ImportError: No module named keras
```
``` r
callr::r(
  function() {
    reticulate::use_condaenv("r-reticulate")
    reticulate::import("keras")
  }
)
#> Error in get_result(output = out, options): callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed
```
```
 Stack trace:

 1. callr::r(function() { ...
 2. callr:::get_result(output = out, options)
 3. throw(new_callr_error(output, killmsg))

 x callr subprocess failed: could not start R, exited with non-zero status, has crashed or was killed 
```

**Comment by gaborcsardi** [comment]
This works fine for me, unfortunately:

```r
❯ callr::r(
+   function() {
+     reticulate::import("keras")
+   }
+ )
<environment: 0x7fec7ac477a0>
attr(,"class")
[1] "python.builtin.module" "python.builtin.object"
```

```r
❯ callr::r(
+   function() {
+     reticulate::use_condaenv("r-reticulate")
+     reticulate::import("keras")
+   }
+ )
<environment: 0x7fec7c8ba938>
attr(,"class")
[1] "python.builtin.module" "python.builtin.object"
```

**Comment by mattwarkentin** [comment]
If the first one worked, then I suppose it's not surprising that the second one also worked. Can you confirm that `keras` only exists in `r-reticulate` environment, and that the first example is not using `r-reticulate`?

**Comment by mattwarkentin** [comment]
For example, when I access my system python from the shell:
```py
Python 3.7.4 (default, Aug 13 2019, 15:17:50) 
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'keras'
>>> 
```

Versus when I acitvate my conda env:
```sh
[0]  /matt/  $ conda activate r-reticulate
[0]  /matt/  $ python
```
```py
Python 3.6.10 |Anaconda, Inc.| (default, Jan  7 2020, 15:01:53) 
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Using TensorFlow backend.
>>> 
```

**Comment by gaborcsardi** [comment]
```
❯ python
Python 2.7.15 (default, Oct  2 2018, 12:50:38)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keras
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named keras
>>>
```

```
❯ R -q

✔ 66.2 MiB
❯ callr::r(
+   function() {
+     reticulate::import("keras")
+   }
+ )
<environment: 0x7fd613a1eae8>
attr(,"class")
[1] "python.builtin.module" "python.builtin.object"
```

**Comment by wlandau** [comment]
Sorry it did not occur to me before, but this might actually be a better issue for `reticulate`.

**Comment by mattwarkentin** [comment]
Yes, @wlandau, you may be right. My suspicion is that when @gaborcsardi invokes a function call from `{reticulate}` that it by default uses the `r-reticulate` environment. This is why he can load `keras` without explicitly specifying the conda env.

I know `{reticulate}` does not use the conda env `r-reticulate` by default (though I am not sure why). Though it doesn't explain why `reticulate::use_condaenv("r-reticulate")` does fix this issue, unless the `{callr}` session is bound to another version of `python` and is unable to use `r-reticulate`.

**Comment by mattwarkentin** [comment]
This may provide some explanation:
``` r
# In a fresh R session
Sys.which("conda")
#> conda 
#>    ""
Sys.which("python")
#>            python 
#> "/usr/bin/python"
```

In my terminal:
```bash
$ which conda
```
```
/opt/anaconda3/bin/conda
```

**Comment by mattwarkentin** [comment]
See rstudio/reticulate#816 for my solution
